export const PLAN_LIMITS = {
  basic: {
    maxItems: 5,
    scanHistoryDays: 7,
    bleTracking: false,
    tagTypes: ['nfc_only'] as const,
    price: 'Free',
    oneLiner: 'Tap to track — perfect for getting started',
    badges: ['5 items', 'Tap-only', '7-day history'],
    tagBuyingGuide: "Search 'NTAG213 NFC sticker' on Flipkart — ₹649 for 10 tags",
  },
  pro: {
    maxItems: 15,
    scanHistoryDays: 30,
    bleTracking: true,
    tagTypes: ['ble_only'] as const,
    price: '₹99/month',
    oneLiner: 'Passive tracking — know where your stuff is, always',
    badges: ['15 items', 'Passive BLE', '30-day history'],
    tagBuyingGuide: "Search 'BLE beacon' on Amazon India — ₹300/tag",
    mostPopular: true,
  },
  max: {
    maxItems: Infinity,
    scanHistoryDays: 90,
    bleTracking: true,
    tagTypes: ['nfc_only', 'nfc_ble', 'ble_only'] as const,
    price: '₹149/month',
    oneLiner: 'Full AirTag-style protection for your most valuable items',
    badges: ['Unlimited', 'Always-on', '90-day history'],
    tagBuyingGuide: "Search 'BLE beacon NTAG213' on Amazon India — ₹200/tag",
  },
} as const;
