/*
 * ===================================================
 *  Poki Lost & Found — BLE Beacon Firmware v4.0
 *  Hardware: ESP32-C3 Super Mini / Dev Module
 * ===================================================
 *
 *  SPRINT 1 UPGRADE — Service UUID advertising
 *  ─────────────────────────────────────────────
 *  Now advertises TWO identifiers simultaneously:
 *
 *  1. Device Name:    "LF-BLE-XXXXXX"
 *     → Detected by Android apps in foreground (name prefix scan)
 *
 *  2. Service UUID:   Custom 128-bit UUID from Poki app
 *     → Detected by iOS apps in background (UUID-based scan)
 *     → Works even when device name is hidden
 *
 *  HOW TO SET UP
 *  ─────────────
 *  1. Open the Poki app → My Items → Add Item → BLE Beacon
 *  2. On the setup screen you will see:
 *       Beacon ID   → paste into BEACON_NAME below
 *       Service UUID → paste into SERVICE_UUID below
 *  3. Flash this sketch to your ESP32-C3
 *  4. Tap "Done" in the app — detection starts immediately
 *
 *  Board: "ESP32C3 Dev Module" in Arduino IDE
 *  Settings: USB CDC On Boot = Enabled
 * ===================================================
 */

#include <BLEDevice.h>
#include <BLEServer.h>
#include <BLEAdvertising.h>
#include <BLEAdvertisementData.h>

// ===================================================
//  CONFIGURATION — paste values from the Poki app
// ===================================================

// Beacon ID — copy from "Your Beacon ID" in the app setup screen
// Example: "LF-BLE-A3F2B1"
#define BEACON_NAME   "LF-BLE-518EEB"

// Service UUID — copy from "Service UUID" in the app setup screen
// Generated by the app, unique per beacon, stored in the database
// Example: "4c4c1a2b-3c4d-4e5f-8a3f-2b1000000000"
#define SERVICE_UUID  "4c4c0000-0000-4000-8000-000000000000"

// LED pin (GPIO 8 confirmed working on ESP32-C3 Super Mini)
#define LED_PIN       8

// Advertising interval in ms: 300=balanced, 1000=battery-saver
// Lower = more detectable + more battery use
#define ADV_INTERVAL_MS  300

// ===================================================
//  GLOBALS
// ===================================================

BLEAdvertising* pAdvertising = nullptr;
unsigned long lastBlink = 0;
unsigned long lastWatchdog = 0;
uint32_t blinkCount = 0;

// ===================================================
//  SETUP
// ===================================================

void setup() {
  Serial.begin(115200);
  pinMode(LED_PIN, OUTPUT);
  delay(2000);

  Serial.println();
  Serial.println("===================================================");
  Serial.println("  Poki Lost & Found Beacon v4.0 (Sprint 1)");
  Serial.println("  Beacon: " + String(BEACON_NAME));
  Serial.println("  UUID:   " + String(SERVICE_UUID));
  Serial.println("===================================================");

  // 3 blinks = starting up
  for (int i = 0; i < 3; i++) {
    digitalWrite(LED_PIN, HIGH); delay(200);
    digitalWrite(LED_PIN, LOW);  delay(200);
  }

  // ── BLE Initialization ──────────────────────────────────────────────────────
  BLEDevice::init(BEACON_NAME);

  // Create a BLE server (required to hold service UUID in advertisement)
  BLEDevice::createServer();

  // Get advertising handle
  pAdvertising = BLEDevice::getAdvertising();

  // ── Advertisement Packet ────────────────────────────────────────────────────
  // The primary advertisement packet contains the Service UUID.
  // This is what iOS and Android read in the background via UUID-based scan.
  BLEAdvertisementData advData;
  advData.setFlags(0x06); // LE General Discoverable | BR/EDR Not Supported

  // Add our custom Service UUID — the critical Sprint 1 addition
  BLEUUID svcUUID(SERVICE_UUID);
  advData.setCompleteServices(svcUUID);

  // ── Scan Response Packet ────────────────────────────────────────────────────
  // The scan response packet contains the device name.
  // Android reads this when it detects the primary advertisement.
  BLEAdvertisementData scanRespData;
  scanRespData.setName(BEACON_NAME);

  pAdvertising->setAdvertisementData(advData);
  pAdvertising->setScanResponseData(scanRespData);

  // Set advertising interval (BLE units = 0.625ms per unit)
  uint16_t advUnits = (uint16_t)(ADV_INTERVAL_MS / 0.625f);
  pAdvertising->setMinInterval(advUnits);
  pAdvertising->setMaxInterval(advUnits + 16); // slight jitter to avoid RF collisions

  // Start broadcasting
  pAdvertising->start();

  Serial.println("✓ Advertising started");
  Serial.println("  Both name AND Service UUID are being broadcast.");
  Serial.println("  Open nRF Connect to verify both appear.");
  Serial.println();

  // 5 rapid blinks = live
  for (int i = 0; i < 5; i++) {
    digitalWrite(LED_PIN, HIGH); delay(80);
    digitalWrite(LED_PIN, LOW);  delay(80);
  }

  lastBlink = millis();
  lastWatchdog = millis();
}

// ===================================================
//  LOOP — heartbeat LED + advertising watchdog
// ===================================================

void loop() {
  unsigned long now = millis();

  // Heartbeat LED: single blink every 3 seconds
  if (now - lastBlink >= 3000) {
    lastBlink = now;
    blinkCount++;

    digitalWrite(LED_PIN, HIGH); delay(80);
    digitalWrite(LED_PIN, LOW);

    // Serial status every ~30 seconds (every 10 blink cycles)
    if (blinkCount % 10 == 0) {
      unsigned long uptime = now / 1000;
      Serial.println("[" + String(uptime) + "s] " + String(BEACON_NAME) +
                     " | beats: " + String(blinkCount));
    }
  }

  // Watchdog: check advertising is still running every 30 minutes
  // (rare ESP32 bug where advertising silently stops after long uptime)
  if (now - lastWatchdog >= 1800000UL) {
    lastWatchdog = now;
    if (!pAdvertising->isAdvertising()) {
      Serial.println("[Watchdog] Advertising stopped — restarting...");
      pAdvertising->start();
      Serial.println("[Watchdog] Advertising restarted.");
    }
  }

  delay(10);
}
